-- MySQL Script generated by MySQL Workbench
-- 04/19/16 18:39:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GStock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GStock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GStock` DEFAULT CHARACTER SET utf8 ;
USE `GStock` ;

-- -----------------------------------------------------
-- Table `GStock`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GStock`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Tva` FLOAT NULL,
  `Specific` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GStock`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GStock`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Category` INT NULL,
  `PurchasePrice` FLOAT NULL,
  `SellingPrice` FLOAT NULL,
  `StockStatus` INT NULL,
  `ModifcationDate` DATE NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `FK_Category_idx` (`Category` ASC),
  CONSTRAINT `FK_Category`
    FOREIGN KEY (`Category`)
    REFERENCES `GStock`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GStock`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GStock`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GStock`.`Provide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GStock`.`Provide` (
  `idProvide` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Tel` VARCHAR(15) NULL,
  `Fax` VARCHAR(15) NULL,
  PRIMARY KEY (`idProvide`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GStock`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GStock`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GStock`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GStock`.`log` (
  `idlog` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Operation` VARCHAR(45) NULL,
  `ProductID` INT NULL,
  `ProviderID` INT NULL,
  `ClientID` INT NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`idlog`),
  INDEX `FK_Product_idx` (`ProductID` ASC),
  INDEX `FK_Client_idx` (`ClientID` ASC),
  INDEX `FK_Provider_idx` (`ProviderID` ASC),
  INDEX `FK_USer_idx` (`UserId` ASC),
  CONSTRAINT `FK_Product`
    FOREIGN KEY (`ProductID`)
    REFERENCES `GStock`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Client`
    FOREIGN KEY (`ClientID`)
    REFERENCES `GStock`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Provider`
    FOREIGN KEY (`ProviderID`)
    REFERENCES `GStock`.`Provide` (`idProvide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USer`
    FOREIGN KEY (`UserId`)
    REFERENCES `GStock`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GStock`.`Mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GStock`.`Mark` (
  `idMark` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Photo` BLOB NULL,
  PRIMARY KEY (`idMark`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GStock`.`ProductByMark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GStock`.`ProductByMark` (
  `idProduct` INT NOT NULL,
  `idMark` INT NOT NULL,
  `photo` FLOAT NULL,
  `SellingPrice` FLOAT NULL,
  `PurchasePrice` FLOAT NULL,
  `Stock` INT NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`idProduct`, `idMark`),
  INDEX `FK_MArk_idx` (`idMark` ASC),
  CONSTRAINT `FK_MArk`
    FOREIGN KEY (`idMark`)
    REFERENCES `GStock`.`Mark` (`idMark`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `GStock`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
